### ISSUE TITLE
Improvement on delete button on create donation

### ISSUE THREAD

**Issue by jinyingtan** [GiftForGood/website#231]
# Feature request

## Is your feature request related to a problem? Please describe.

No.

## Describe the solution you'd like

On the current implementation, the delete button is quite hard to see.   
I think we can add background color to the delete button to make it more obvious. 

## Additional context

![IMG_2423](https://user-images.githubusercontent.com/29192918/89093326-0520ce00-d3ec-11ea-8003-1cbc5a1c00f1.PNG)

**Comment by jamessspanggg** [comment]
Fixed
