### ISSUE TITLE
[BUG] Auth API

### ISSUE THREAD

**Issue by kohchihao** [GiftForGood/website#87]
# Bug report

## Describe the bug
- within the `_createDonor` method, the `_doesDonorExist` returns false even though the user exists already. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. call `registerDonorWithGoogle` or `registerDonorWithEmailAndPassword`

## Expected behavior

- The donor shouldn't be created again if already exists.

**Comment by jinyingtan** [comment]
Cannot replicate
